# Generated by Django 5.2.7 on 2025-10-31 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='materiais/')),
                ('texto_extraido', models.TextField(blank=True, help_text='Cache do texto extraído do PDF.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaGerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pergunta', models.TextField()),
                ('justificativa', models.TextField(help_text='Explicação da resposta correta (fornecida pela IA).')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='core.material')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_alternativa', models.CharField(max_length=500)),
                ('eh_correta', models.BooleanField(default=False, help_text='Definido pela IA como a resposta correta.')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='core.perguntagerada')),
            ],
        ),
        migrations.CreateModel(
            name='TentativaQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.IntegerField(default=0)),
                ('concluido_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foi_correta', models.BooleanField()),
                ('alternativa_selecionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alternativa')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perguntagerada')),
                ('tentativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.tentativaquiz')),
            ],
        ),
    ]
